version: 2
jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            terraform init
            terraform validate
  terraform-plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            terraform init
            terraform plan
  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            terraform init
            # terraform apply
            mkdir state_file
            touch terraform.tfstate
            cp terraform.tfstate state_file/terraform.tfstate
            pwd
            ls
      - persist_to_workspace:
          root: /
          paths:
            - /
  terraform-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Terraform Destroy
          command: |
            # terraform init
            # terraform destroy
            echo "Destroy time"
            pwd
            ls
workflows:
  version: 2
  code-testing:
    jobs:
      - terraform-validate
      - terraform-plan:
          requires:
            - terraform-validate
      - terraform-apply:
          requires:
            - terraform-plan
      - terraform-destroy:
          requires:
            - terraform-apply