version: 2
jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            terraform validate
workflows:
  version: 2
  code-testing:
    jobs:
      - terraform-validate